# Generated by Django 5.1.1 on 2024-09-07 20:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_polls', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunch_polls.user')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunch_polls.menu')),
            ],
            options={
                'unique_together': {('employee', 'menu')},
            },
        ),
    ]
