# Generated by Django 5.1.1 on 2024-09-08 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_polls', '0004_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='days_of_week',
            new_name='day_of_week',
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('restaurant', 'day_of_week')},
        ),
    ]
