# Generated by Django 5.1.1 on 2024-09-08 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_polls', '0007_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='menu',
            new_name='menu_id',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='employee',
            new_name='user_id',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user_id', 'menu_id')},
        ),
    ]
