# Generated by Django 5.1.1 on 2024-09-08 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_polls', '0008_rename_menu_vote_menu_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
    ]
